import cv2, numpy as np, time
image = cv2.imread('data/images/people.jpg', 0)
t1 = time.time()
clahe = cv2.createCLAHE(2, (8, 8))
new_image = clahe.apply(image)
t2 = time.time()
cv2.imshow('hi2', new_image)
cv2.imshow('hi', image)
cv2.waitKey(0)
print(t2 - t1)